---
- name: Install samba
  apt:
    pkg: samba
    state: present

- name: configure samba
  copy:
    src: '{{ samba_config_file }}'
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'

- name: Create samba users
  shell: >
    (pdbedit -L | grep {{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  with_items: '{{ samba_users }}'
  when: samba_users|length
  changed_when: false
